apps_assurance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',include('client.urls')),
    path('formulaire_vehicule/',include('vehicule.urls')),
    path('affiche_assurance/',include('assure.urls')),
    path('typeassurance/',include('typeassurance.urls')),
    path('affiche_sinitre/',include('sinistre.urls')),
    path('formulaire_adherant/',include('adherant.urls')),
    path('home/',include('traitementForm.urls')),
    path('login/',include('compte.urls'))
    
    
]

assure/urls.py
from django.urls import path
from .import views

app_name='affiche_assurance'
urlpatterns=[
    path('',views.affiche_assurance,name='affiche_assurance')
]

compte/urls.py
from django.urls import path
from .import views

app_name='compte'
urlpatterns=[
    path('inscription/',views.inscription,name='inscription'),
    path('acces/',views.acces,name='acces'),
    path('deconnecter/',views.deconnecter,name='deconnecter')
    ]

traitementForm/urls.py
from django.urls import path
from .import views

app_name='traitementForm'
urlpatterns=[
    path('',views.home,name='home'),
    path('formulaire_adherant/',views.enregistrerAdherant,name='formulaire_adherant'),
     path('formulaire_voiture/',views.enregistrerVoiture,name='formulaire_voiture'),
     path('list_adherant/',views.list_adherant,name='list_adherant'),
    path('detail_adherant/<str:pk>',views.detail_adherant,name='detail_adherant'),
    path('modifier_detail_adherant/<str:pk>',views.modifier_detail_adherant,name='modifier_detail_adherant'),
    path('suprimer_adherant/<str:pk>',views.suprimer_adherant,name='suprimer_adherant'),
    path('list_vehicule/',views.list_vehicule,name='list_vehicule'),
    path('afficher_detail_voiture/<str:pk>',views.afficher_detail_voiture,name='afficher_detail_voiture'),
    path('modifier_detail_vehicule/<str:pk>',views.modifier_detail_vehicule,name='modifier_detail_vehicule'),
    path('suprimer_vehicule/<str:pk>',views.suprimer_vehicule,name='suprimer_vehicule'),
    path('list_sinistre/',views.list_sinistre,name='list_sinistre'),
    path('enregistrerSinistre/',views.enregistrerSinistre,name='enregistrerSinistre'),
    path('afficher_detail_sinistre/<str:pk>',views.afficher_detail_sinistre,name='afficher_detail_sinistre'),
    path('modifier_detail_sinistre/<str:pk>',views.modifier_detail_sinistre,name='modifier_detail_sinistre'),
    path('suprimer_sinistre/<str:pk>',views.suprimer_sinistre,name='suprimer_sinistre'),
    path('list_assurance/',views.list_assurance,name='list_assurance'),
    path('afficher_assurance/<str:pk>',views.afficher_assurance,name='afficher_assurance'),
    path('enregistrement_assurance/',views.enregistrement_assurance,name='enregistrement_assurance'),
    path('modifier_detail_assurance/<str:pk>',views.modifier_detail_assurance,name='modifier_detail_assurance'),
    path('suprimer_sinistre/<str:pk>',views.suprimer_sinistre,name='suprimer_sinistre'),
    
    
    
    
    
    
]

assure/models.py
from django.db import models
from typeassurance.models import typeassurance
# Create your models here.
class assure(models.Model):
    typ_fractionnement=(('mensuel','mensuel'),('annuel','annuel'))
    type_ass=models.ForeignKey(typeassurance,null=True, on_delete=models.SET_NULL)
    date_debut=models.DateField()
    fractionnement=models.CharField(max_length=200,null=True, choices=typ_fractionnement)
    date_ex=models.DateField()
    numero_assurance=models.CharField(max_length=200,null=True)
    
    def __str__(self) -> str:
        return str(self.type_ass)

traitementForm/models.py
from django.db import models

# Create your models here.

traitementForm/forms.py
from django import forms
from django.forms import ModelForm
from adherant.models import adherant
from vehicule.models import vehicule
from sinistre.models import sinistre
from assure.models import assure
from django.contrib.auth.forms import  UserCreationForm
from django.contrib.auth.models import User


class FormulaireAdherant(ModelForm):
    #cette classe permet de creer un formulaire d'enregistremment des adherants et d'ajouter le propriete bootstrap selon le template fournis
    matricule=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    nom=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    prenom=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    date_naissance=forms.DateField(widget=forms.DateInput(attrs={"class":"form-control form-input"}))
    telephone=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    adresse=forms.CharField(widget=forms.Textarea(attrs={"class":"form-control form-input","cols":30,"rows":5}))
    
    class Meta:
        model=adherant
        fields=('matricule','nom','prenom','date_naissance', 'telephone','adresse')

class FormulaireVoiture(ModelForm):
    #cette classe permet de creer un formulaire d'enregistremment de voiture et d'ajouter le propriete bootstrap selon le template fournis
    marque=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    model_v=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    immatriculation=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    anne_mis_circulation=forms.DateField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    anne_de_fabrication=forms.DateField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    
    class Meta:
        model=vehicule
        fields=('proprietaire','marque','model_v','immatriculation', 'anne_mis_circulation','anne_de_fabrication','type_carburant')

class FormulaireSinistre(ModelForm):
    #cette classe permet de creer un formulaire d'enregistremment de sinistre et d'ajouter le propriete bootstrap venant selon le template fournis
    date_debut=forms.DateField(widget=forms.TextInput(attrs={'class':"form-control form-input"}))
    justification=forms.CharField(widget=forms.Textarea(attrs={'class':"form-control form-input","cols":30,"rows":5}))
    class Meta:
        model=sinistre
        fields=('assure','adherant','date_debut','justification')
        
class FormulaireAssure(ModelForm):
    #cette classe permet de creer un formulaire et d'ajouter le propriete bootstrap venant selon le template fournis
    date_debut=forms.DateField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    date_ex=forms.DateField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    numero_assurance=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input"}))
    class Meta:
        model=assure
        fields=('type_ass','date_debut','fractionnement','date_ex', 'numero_assurance')
        


class CreerUtilisateur(UserCreationForm): 
#cette classe permet de generer le formulaire et d'ajouter le propriete bootstrap depuis le template qui genere le formulaire de creation de compte
    username=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input","placeholder":"Votre nom d'utilisateur"}))
    email=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control form-input","placeholder":"Votre adresse mail"}))
    password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control form-input","placeholder":"Votre nouveau mot de passe"}))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control form-input","placeholder":"Confirmer votre mot de passe"}))
    class Meta:
        model=User
        fields=['username','email','password1','password2']

assure/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def affiche_assurance(request):
    return HttpResponse('application assurer')

traitementForm/views.py
from django.shortcuts import render
from adherant.models import adherant
from vehicule.models import vehicule
from .forms import FormulaireAdherant
from .forms import FormulaireVoiture
from sinistre.models import sinistre
from vehicule.models import vehicule
from assure.models import assure
from .forms import FormulaireAssure
from .forms import FormulaireSinistre
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url='compte:acces')#cette focntion consite a rediriger l'utisateur vers l'interface d'authenfication
def home(request):
    #cette fonction permet afficher le tableau de bord 
    
    nombre_client=adherant.objects.all().count()#cette variable consiste à stocker le nombre d'occurence entrer(le nombre d'adherant)
    nombre_voiture=vehicule.objects.all().count()#cette variable consiste à stocker le nombre d'occurence entrer(le nombre des vehicule)
    nombre_sinistre=sinistre.objects.all().count()#cette variable consiste à stocker le nombre d'occurence entrer(le nombre de sinistre)
    nombre_assurance=assure.objects.all().count()#cette variable consiste à stocker le nombre d'occurence entrer(le nombre d'assurance)
    context={'nombre_client':nombre_client,'nombre_voiture':nombre_voiture,'nombre_sinistre':nombre_sinistre,'nombre_assurance':nombre_assurance}
    return render(request,'dashbord/dashboard.html',context)

@login_required(login_url='compte:acces')
def list_adherant(request):#cette fonction consiste à afficher la liste d'adherant enregistrer 
    form=adherant.objects.all()
    context={'form':form}
    return render(request,'client/client.html',context)

@login_required(login_url='compte:acces')       
def enregistrerAdherant(request): #cette fonction consiste à enregistrer les nouveaux adherant 
    form=FormulaireAdherant()
    if request.method == 'POST':
       form=FormulaireAdherant(request.POST)
       if form.is_valid:
           form.save()
           context={'form':form}
           return render(request,'client/client-insert-update.html',context)
    context={'form':form}
    return render(request,'client/client-insert-update.html',context)

@login_required(login_url='compte:acces')
def enregistrerVoiture(request):#cette fonction consiste à enregistrer les nouvelles voitures
    form=FormulaireVoiture()
    if request.method == 'POST':
       form=FormulaireVoiture(request.POST)
       if form.is_valid:
           form.save()
    context={'form':form}
    return render(request,'vehicule/vehicule-insert-update.html',context)

@login_required(login_url='compte:acces')
def detail_adherant(request,pk):#cette fonction consiste à afficher les information sur une occurence(les informations sur l'adherants) grace à sa cle etrangere
    form=adherant.objects.get(id=pk)
    context={"form":form}
    return render(request,'client/client-details.html',context)

@login_required(login_url='compte:acces')
def modifier_detail_adherant(request,pk): #cette fonction consiste à modifier les information sur une occurence(les informations sur l'adherants) grace à sa cle etrangere
    ident=adherant.objects.get(id=pk)
    form=FormulaireAdherant(instance=ident)
    if request.method == 'POST':
        form=FormulaireAdherant(request.POST,instance=ident)
        if form.is_valid():
            form.save()
            form = adherant.objects.all()
            context = {'form': form}
            return render(request,'client/client.html',context)  
    context={'form':form}
    return render(request, 'client/client-insert-update.html', context)
    
@login_required(login_url='compte:acces')
def suprimer_adherant(request,pk):#cette fonction consiste à suprimer une occurence(l'adherants) grace à sa cle etrangere
     ident_adherant=adherant.objects.get(id=pk)
     ident_adherant.delete()
     form = adherant.objects.all()
     context = {'form': form}
     return render(request,'client/client.html',context)

@login_required(login_url='compte:acces')
def list_vehicule(request):#cette fonction consiste à afficher la liste des vehicules enregistrer 
    form=vehicule.objects.all() 
    context={'form':form}
    return render(request,'vehicule/vehicule.html',context)

@login_required(login_url='compte:acces')
def afficher_detail_voiture(request,pk):#cette fonction consiste à afficher la liste des vehicules enregistrer 
    form=vehicule.objects.get(id=pk)
    context={"form":form}
    return render(request,'vehicule/vehicule-details.html',context)

@login_required(login_url='compte:acces')
def  modifier_detail_vehicule(request,pk):#cette fonction consiste à afficher les information sur une occurence(les informations sur la voiture) grace à sa cle etrangere
     ident_vehicule=vehicule.objects.get(id=pk)
     form=FormulaireVoiture(instance=ident_vehicule)
     if request.method =='POST':
         form=FormulaireVoiture(request.POST,instance=ident_vehicule)
         if form.is_valid():
             form.save()
             form=vehicule.objects.all()
             context={'form':form}
             return render(request,'vehicule/vehicule.html',context)
    
     context={'form':form}
     return render(request, 'vehicule/vehicule-insert-update.html', context)

@login_required(login_url='compte:acces') 
def suprimer_vehicule(request,pk):
     ident_vehicule=vehicule.objects.get(id=pk)
     ident_vehicule.delete()
     form=vehicule.objects.all()
     context={'form':form}
     return  render(request,'vehicule/vehicule.html',context)
        
@login_required(login_url='compte:acces')
def list_sinistre(request):
    form=sinistre.objects.all()
    context={'form':form}
    return render(request,'sinistre/sinistre.html',context)

@login_required(login_url='compte:acces')
def enregistrerSinistre(request):
    form=FormulaireSinistre()
    if request.method == 'POST':
        form=FormulaireSinistre(request.POST)
        if form.is_valid:
            form.save()
            context={'form':form}
            return render(request,'sinistre/sinistre-insert-update.html',context)
    context={'form':form}
    return render(request,'sinistre/sinistre-insert-update.html',context)

@login_required(login_url='compte:acces')
def afficher_detail_sinistre(request,pk):
    ident_sinitre= sinistre.objects.get(id=pk)
    context={'form':ident_sinitre}
    return render(request,'sinistre/sinistre-details.html',context)

@login_required(login_url='compte:acces')
def modifier_detail_sinistre(request,pk):
    ident_sinistre=sinistre.objects.get(id=pk)
    form=FormulaireSinistre(instance=ident_sinistre)
    if request.method == 'POST':
        form=FormulaireSinistre(request.POST,instance=ident_sinistre)
        form.is_valid()
        form.save()
        form=sinistre.objects.all()
        context={'form':form}
        return render(request,'sinistre/sinistre.html',context)
    
    context={'form':form}
    return render(request,'sinistre/sinistre-insert-update.html',context)
   
@login_required(login_url='compte:acces')
def suprimer_sinistre(request,pk):
    form=sinistre.objects.get(id=pk)
    form.delete()
    form=sinistre.objects.all()
    context={'form':form}
    return render(request,'sinistre/sinistre.html',context)

@login_required(login_url='compte:acces')
def list_assurance(request):
    form=assure.objects.all()
    context={'form':form}
    return render(request,'assure/assurance.html',context)

@login_required(login_url='compte:acces')
def afficher_assurance(request,pk):
    form=assure.objects.get(id=pk)
    form_vehicule=vehicule.objects.get(id=pk)
    context={'form':form,'form_vehicule':form_vehicule}
    return render(request,'assure/assurance-details.html',context)

@login_required(login_url='compte:acces')
def enregistrement_assurance(request):
    form=FormulaireAssure()
    if request.method == 'POST':
         form=FormulaireAssure(request.POST)
         if form.is_valid():
            form.save()
            context={'form':form}
            return render(request,'assure/assurance-insert-update.html',context)
    context={'form':form}
    return render(request,'assure/assurance-insert-update.html',context)   
    
@login_required(login_url='compte:acces')
def modifier_detail_assurance(request,pk):
    ident_assurance=assure.objects.get(id=pk)
    form=FormulaireAssure(instance=ident_assurance)
    if request.method == 'POST':
        form=FormulaireAssure(request.POST,instance=ident_assurance)
        if form.is_valid():
            form.save()
            form=assure.objects.all()
            context={'form':form}
            return render(request,'assure/assurance.html',context)
    
    context={'form':form}
    return render(request,'assure/assurance-insert-update.html',context)

@login_required(login_url='compte:acces')
def suprimer_assurance(request,pk):
    form=assure.objects.get(id=pk)
    form.delete()
    form=assure.objects.all()
    context={'form':form}
    return render(request,'assure/assurance.html',context)

traitementForm/templates/assure/assurance-details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GBC - Assurance</title>

    <link rel="stylesheet" href="{% static 'entities/assurance/assurance.css' %}">
    <link rel="stylesheet" href="{% static 'entities/assurance/assurance-detail.css' %}">
    <link rel="stylesheet" href="{% static 'layouts/siberbar/siberbar.css' %}">
    <script src="{% static 'asset/lib/bootstrap-5.1.3-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'asset/lib/font-awasome/js/all.min.js' %}"></script>
</head>
<body>
    <div class="container-fluid">
        <!-- nav-bar  -->
        <div class="row">
            <div class="col-lg-2 col-md-12 col-sm-12 navbar-dark bg-dark bg-nav-title">
                <a href="http://">GBC  ASSURANCE</a>
            </div>
            <div class="navbar navbar-expand-lg navbar-light bg-light col-lg-10 col-md-12 col-sm-12">
                <nav>
                    <div class="navbar-menu-items" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link"  href="http://">
                                <span class="fa fa-users"></span><span class="user-profil">Français</span>
                            </a>
                            </li>
                            <li class="nav-item dropdown">                           
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="fa fa-users"></span><span class="user-profil">Mon compte</span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="#">Mon profil</a></li>
                                <li><a class="dropdown-item" href="#">Chris Mbenza</a></li>
                                <li><a class="dropdown-item" href="#">A propos</a></li>
                                <hr class="">
                                <li><a class="dropdown-item" href="#">Paramétres</a></li>
                                <li><a class="dropdown-item" href="{% url 'compte:deconnecter' %}">Déconnexion</a></li>
                            </ul>
                            </li>
                        </ul>
                        </div>                  
                </nav>
            </div>
        </div>
        <!-- #nav-bar  -->  
        
        <div class="row">
        <div class="col-2 siberbard">
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-table"></span>
                <span style="margin-left: 0.56rem;">Tableau de bord</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Client</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Sinistre</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Véhicule</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Echéance</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action active"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Assurance</span>
                </a>
            </div>
        </div>

        <div class="col-10 form-panel">                
        <!-- header-dashboard -->
        <div class="row header">
          <div class="col-lg-1 col-sm-0"></div>
          <div class="col-lg-8 col-sm-12">
            <h2 id="page-heading">
              <span class="title-header">assurance/détails</span>        
              <button class="btn btn-primary" style="background-color: #6547dc;">
                  <fa-icon class="fa fa-arrow-left"></fa-icon>
                  <span>
                  Retour
                  </span>
              </button>            
              <button class="btn btn-primary" style="background-color: #4389f1;">
                  <fa-icon class="fa fa-edit"></fa-icon>
                  <span>
                   porter un changement
                  </span>
              </button>
          </h2>
          <div class="card" style="width: auto;">
          <div class="card-body">
        
            <div class="row mb-3">
                <div class="col-6">
              <div class="display-1">Individuel accident</div>
              <div class="lead">{{form.type_ass}}</div>
                </div>  
            <div class="col-6">
              <div class="display-1">Date de debut</div>
              <div class="lead">{{form.date_debut}}</div>
            </div>
            </div>  
            <div class="row mb-3">
                <div class="col-6">
                    <div class="display-1">fractionnement</div>
                    <div class="lead">{{form.fractionnement}}</div>
                </div>   
                <div class="col-6">
                    <div class="display-1">date d'expiration</div>
                    <div class="lead">{{form.date_ex}}</div>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-6">
                    <div class="display-1">numero d'assurance</div>
                    <div class="lead">{{form.numero_assurance}}</div>
                </div>   
                <div class="col-6">
                    <div class="display-1">Objet assuré</div>
                   
                </div>
            </div>  
            
            </div>  
          </div>
          </div>  
        </div>
        <div class="col-lg-1 col-sm-0"></div>
        <!-- #header-dashboard  -->
 
        </div>
        </div>
    </div>
</body>
</html>

traitementForm/templates/assure/assurance.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GBC - Assurance</title>

    <link rel="stylesheet" href="{% static 'entities/assurance/assurance.css' %}">
    <link rel="stylesheet" href="{% static 'layouts/siberbar/siberbar.css' %}">
    <script src="{% static 'asset/lib/bootstrap-5.1.3-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'asset/lib/font-awasome/js/all.min.js' %}"></script>
</head>
<body>
    <div class="container-fluid">
        <!-- nav-bar  -->
        <div class="row">
            <div class="col-lg-2 col-md-12 col-sm-12 navbar-dark bg-dark bg-nav-title">
                <a href="http://">GBC  ASSURANCE</a>
            </div>
            <div class="navbar navbar-expand-lg navbar-light bg-light col-lg-10 col-md-12 col-sm-12">
                <nav>
                    <div class="navbar-menu-items" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Reports</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link"  href="http://">
                                <span class="fa fa-users"></span><span class="user-profil">Français</span>
                            </a>
                            </li>
                            <li class="nav-item dropdown">                           
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="fa fa-users"></span><span class="user-profil">Mon compte</span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="#">Mon profil</a></li>
                                <li><a class="dropdown-item" href="#">Chris Mbenza</a></li>
                                <li><a class="dropdown-item" href="#">A propos</a></li>
                                <hr class="">
                                <li><a class="dropdown-item" href="#">Paramétres</a></li>
                                <li><a class="dropdown-item" href="{% url 'compte:deconnecter' %}">Déconnexion</a></li>
                            </ul>
                            </li>
                        </ul>
                        </div>                  
                </nav>
            </div>
        </div>
        <!-- #nav-bar  -->  
        
        <div class="row">
        <div class="col-2 siberbard">
            <div class="list-group">
                <a href="{% url 'traitementForm:home' %}" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-table"></span>
                <span style="margin-left: 0.56rem;">Tableau de bord</span>
                </a>
                <a href="{% url 'traitementForm:list_adherant' %}" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Client</span>
                </a>
                <a href="{% url 'traitementForm:list_sinistre' %}" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Sinistre</span>
                </a>
                <a href="{% url 'traitementForm:list_vehicule' %}" class="list-group-item list-group-item-action"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Véhicule</span>
                </a>
                <a href="{% url 'traitementForm:list_assurance' %}" class="list-group-item list-group-item-action active"
                aria-current="true"><span class="fa fa-home"></span>
                <span style="margin-left: 0.56rem;">Assurance</span>
                </a>
            </div>
        </div>

        <div class="col-10 form-panel">                
        <!-- header-dashboard -->
        <div class="row header">
            <div class="col-lg-12 col-sm-12">
                <h2 id="page-heading">
                    <span class="title-header">assurance</span>        
                    <button class="btn btn-primary" style="background-color: #6547dc;">
                        <fa-icon class="fa fa-arrow-left"></fa-icon>
                        <span>
                        Retour
                        </span>
                    </button>            
                    <button class="btn btn-primary" style="background-color: #4389f1;">
                        <fa-icon class="fa fa-plus"></fa-icon>
                        <span>
                        Nouvelle assurance
                        </span>
                    </button>
                </h2>
                <!-- <hr class=""> -->
            </div> 
        </div>
        <!-- #header-dashboard  -->

        <!-- tableau  -->
        <div class="table-responsive" id="entities">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Individuel accident</th>
                    <th scope="col">Date de debut</th>
                    <th scope="col">fractionnement</th>
                    <th scope="col">date d'expiration</th>
                    <th scope="col">numero_assurance</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                {% for form in form %}
                <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>{{form.type_ass}}</td>
                    <td>{{form.date_debut}}</td>
                    <td>{{form.fractionnement}}</td>
                    <td>{{form.date_ex}}</td>
                    <td>{{form.numero_assurance}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <a  href="{% url 'traitementForm:afficher_assurance' form.id %}"
                                class="btn btn-info btn-sm text-white">
                                <fa-icon class="fa fa-edit"></fa-icon>
                                <span class="d-none d-md-inline">Afficher</span>
                            </a>

                            <a href="{% url 'traitementForm:modifier_detail_assurance' form.id %}"
                                class="btn btn-primary btn-sm">
                                <fa-icon class="fa fa-edit"></fa-icon>
                                <span class="d-none d-md-inline">Modifier</span>
                            </a>

                            <a href="{% url 'traitementForm:suprimer_sinistre' form.id %}"
                                class="btn btn-danger btn-sm">
                                <fa-icon class="fa fa-edit"></fa-icon>
                                <span class="d-none d-md-inline">Suprimer</span>
                        </a>
                        </div>
                    </td>
                </tr>  
                </tbody>
                {% endfor %}
            </table>
        </div>
        <!-- #tableau  -->
        </div>
        </div>
    </div>
</body>
</html>